package hellocucumber;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.safari.SafariDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class FreseniusTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public void setUp() throws MalformedURLException, InterruptedException {
    //driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    //System.setProperty("webdriver.chrome.driver", "/Users/arpit.kumar.vaish/Drivers/chromedriver");
    //new ChromeDriver();
    WebDriver driver = new SafariDriver();
    driver.get("http://127.0.0.1:8000/deviceStatistics/devices");
    driver.manage().window().maximize();


    driver.findElement(By.id("id_username")).sendKeys("admin");
    driver.findElement(By.id("id_password")).sendKeys("Admin123");
    driver.findElement(By.xpath("//*[@value='Log in']")).click();

    Thread.sleep(9000);
    driver.close();
    //driver.quit();
  }

  public void tearDown() {
    driver.quit();
  }



  public void fresenius() {
    //driver.get("http://127.0.0.1:8000/deviceStatistics/devices");
    //driver.manage().timeouts().implicitlyWait(1, TimeUnit.MINUTES);
    //driver.get("google.com");
    //driver.manage().window().setSize(new Dimension(1680, 948));
    /*driver.findElement(By.linkText("APTCOM2")).click();
    driver.findElement(By.cssSelector("td:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-primary:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".btn-primary:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".btn-outline-warning:nth-child(4)")).click();
    driver.findElement(By.id("Batch")).click();
    driver.findElement(By.id("Batch")).sendKeys("Batch_1");
    driver.findElement(By.name("run_statistics")).click();*/
    //driver.close();
  }
}
